[build]
builder = "DOCKERFILE"
dockerfilePath = "bot-runner/Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = ""
healthcheckTimeout = 0
